services:

  frontend:
    container_name: attack-workbench-frontend
    image: ghcr.io/center-for-threat-informed-defense/attack-workbench-frontend:${ATTACKWB_FRONTEND_VERSION:-latest}
    # Uncomment the following line to build from source (the path assumes that the source code is cloned in a directory adjacent to this repo)
    # build: ../attack-workbench-frontend
    depends_on:
     - rest-api
    ports:
      - "${ATTACKWB_FRONTEND_HTTP_PORT:-80}:${ATTACKWB_FRONTEND_HTTP_PORT:-80}"
    volumes:
      - ./configs/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  rest-api:
    container_name: attack-workbench-rest-api
    image: ghcr.io/center-for-threat-informed-defense/attack-workbench-rest-api:${ATTACKWB_RESTAPI_VERSION:-latest}
    # Uncomment the following line to build from source (the path assumes that the source code is cloned in a directory adjacent to this repo)
    # build: ../attack-workbench-rest-api
    depends_on:
      - database
    ports:
      - "${ATTACKWB_RESTAPI_HTTP_PORT:-3000}:${ATTACKWB_RESTAPI_HTTP_PORT:-3000}"
    volumes:
      - ./configs/rest-api/rest-api-service-config.json:/usr/src/app/resources/rest-api-service-config.json:ro
    env_file:
      - ./configs/rest-api/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    container_name: attack-workbench-database
    image: mongo:5
    ports:
      - "${ATTACKWB_DB_PORT:-27017}:${ATTACKWB_DB_PORT:-27017}"
    volumes:
      - workspace-data:/data/db
      - ./database-backup:/dump
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  taxii:
    container_name: attack-workbench-taxii-server
    image: ghcr.io/mitre-attack/attack-workbench-taxii-server:${ATTACKWB_TAXII_VERSION:-latest}
    # Uncomment the following line to build from source (the path assumes that the source code is cloned in a directory adjacent to this repo)
    # build: ../attack-workbench-taxii-server
    depends_on:
      - rest-api
    ports:
      - "${ATTACKWB_TAXII_HTTP_PORT:-5002}:${ATTACKWB_TAXII_HTTP_PORT:-5002}"
    volumes:
      - ./configs/taxii/config:/app/config:ro
    environment:
      - TAXII_ENV=${ATTACKWB_TAXII_ENV:-dev}
      - TAXII_HYDRATE_ON_BOOT=true
    profiles:
      - with-taxii
    restart: unless-stopped

volumes:
  workspace-data:
