apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
- configmap-rest-api-prod.yaml
- configmap-taxii-prod.yaml
- deployment-patches.yaml

replicas:
- name: frontend
  count: 2
- name: rest-api
  count: 2
- name: taxii
  count: 1

images:
- name: ghcr.io/center-for-threat-informed-defense/attack-workbench-frontend
  newTag: stable
- name: ghcr.io/center-for-threat-informed-defense/attack-workbench-rest-api
  newTag: stable
- name: ghcr.io/mitre-attack/attack-workbench-taxii-server
  newTag: stable