apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Uncomment to include TAXII for local testing:
# components:
# - ../../components/taxii

labels:
- pairs:
    environment: local
  includeSelectors: false

patches:
- path: patch-resources.yaml
- path: patch-rest-api-env.yaml
- target:
    kind: Ingress
    name: attack-workbench-ingress
  path: patch-ingress.yaml
