apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment-taxii.yaml
- service-taxii.yaml
- configmap-taxii.yaml
- secret-taxii.yaml
- memcached.yaml

# Patch the base Ingress to add /taxii route
patches:
- target:
    kind: Ingress
    name: attack-workbench-ingress
  patch: |-
    - op: add
      path: /spec/rules/0/http/paths/-
      value:
        path: /taxii
        pathType: Prefix
        backend:
          service:
            name: attack-workbench-taxii
            port:
              number: 8000
