apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memcached
        app.kubernetes.io/component: cache
    spec:
      containers:
      - name: memcached
        image: memcached:1.6-alpine
        args: ["-m", "4096", "-I", "50m"]
        ports:
        - name: memcached
          containerPort: 11211
        livenessProbe:
          tcpSocket:
            port: memcached
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: memcached
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "4Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: attack-workbench-taxii-cache
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
  - name: memcached
    port: 11211
    targetPort: memcached
  selector:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
