apiVersion: v1
kind: Secret
metadata:
  name: taxii-secrets
  labels:
    app.kubernetes.io/name: taxii
    app.kubernetes.io/component: taxii-server
type: Opaque
stringData:
  # Base64 encoded "taxii-server:secret-squirrel" for REST API service auth
  TAXII_WORKBENCH_AUTH_HEADER: ""
