apiVersion: v1
kind: Service
metadata:
  name: attack-workbench-taxii
  labels:
    app.kubernetes.io/name: taxii
    app.kubernetes.io/component: taxii-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: taxii
    app.kubernetes.io/component: taxii-server
