apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: attack-workbench
data:
  nginx.conf: |
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      server {
        listen 80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location / {
          try_files $uri $uri/ /index.html;
        }

        location /api {
          client_max_body_size 50M;

          # Disable buffering for SSE streams
          proxy_buffering off;
          proxy_cache off;

          # Keep connection alive for long-running requests
          proxy_read_timeout 600s;
          proxy_connect_timeout 300s;
          proxy_send_timeout 300s;

          # Required headers for SSE
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding on;

          # Disable compression for SSE
          gzip off;

          proxy_pass http://attack-workbench-rest-api:3000;
        }
      }
    }