apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-api-config
data:
  rest-api-service-config.json: |
    {
      "serviceAuthn": {
        "basicApikey": {
          "enable": false,
          "serviceAccounts": []
        },
        "challengeApikey": {
          "enable": false,
          "serviceAccounts": []
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-api-env
data:
  PORT: "3000"
  CORS_ALLOWED_ORIGINS: "*"
  NODE_ENV: "production"
  WB_REST_DATABASE_MIGRATION_ENABLE: "true"
  AUTHN_MECHANISM: "anonymous"
  AUTHN_OIDC_ISSUER_URL: ""
  AUTHN_OIDC_REDIRECT_ORIGIN: ""
  SERVICE_ACCOUNT_OIDC_ENABLE: "false"
  JWKS_URI: ""
  WB_REST_SERVICE_ACCOUNT_CHALLENGE_APIKEY_ENABLE: "false"
  WB_REST_TOKEN_TIMEOUT: "300"
  WB_REST_SERVICE_ACCOUNT_BASIC_APIKEY_ENABLE: "false"
  DEFAULT_INTERVAL: "300"
  JSON_CONFIG_PATH: ""
  LOG_LEVEL: "info"
  WB_REST_STATIC_MARKING_DEFS_PATH: "./app/lib/default-static-marking-definitions/"
  ALLOWED_VALUES_PATH: "./app/config/allowed-values.json"
  CHECK_WORKBENCH_INTERVAL: "10"
  ENABLE_SCHEDULER: "true"
