apiVersion: v1
kind: Service
metadata:
  name: attack-workbench-rest-api
  namespace: attack-workbench
  labels:
    app: rest-api
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: attack-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: ghcr.io/center-for-threat-informed-defense/attack-workbench-rest-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: rest-api-env
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/resources/rest-api-service-config.json
          subPath: rest-api-service-config.json
        livenessProbe:
          httpGet:
            path: /api/health/ping
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health/ping
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: rest-api-config