apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: attack-workbench

resources:
- namespace.yaml
- configmap-nginx.yaml
- configmap-rest-api.yaml
- secret-rest-api.yaml
- deployment-frontend.yaml
- service-frontend.yaml
- deployment-rest-api.yaml
- service-rest-api.yaml
- statefulset-mongodb.yaml
- service-mongodb.yaml
- ingress.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: attack-workbench
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false

images:
- name: ghcr.io/mitre-attack/attack-workbench-frontend
  newTag: latest
- name: ghcr.io/mitre-attack/attack-workbench-rest-api
  newTag: latest
- name: mongo
  newName: mongo
  newTag: "8"
