apiVersion: v1
kind: Service
metadata:
  name: attack-workbench-rest-api
  labels:
    app.kubernetes.io/name: rest-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: rest-api
    app.kubernetes.io/component: api
