apiVersion: v1
kind: Service
metadata:
  name: attack-workbench-database
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
